services:
  crabot_fastapi_app:
    container_name: crabot_fastapi_app
    build: crabot_fastapi_app/
    volumes:
      - ./crabot_fastapi_app:/crabot_fastapi_app
    ports:
      - ${FASTAPI_APP_PORT}:${FASTAPI_APP_PORT}
    restart: unless-stopped
    environment:
      - nezka_encryption_key
      # - aonika_encryption_key
      # - razrab_encryption_key
      - STEAM_ACCOUNT_SECRET_KEY
      - STOCK_TRANSFER_FASTAPI_API_KEY
      - OPTIONAL_FLAG=${OPTIONAL_FLAG:-off}
    env_file:
      - .env
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port ${FASTAPI_APP_PORT} --reload"

